### ISSUE TITLE
Unable to run provision.sh script

### ISSUE THREAD

**Issue by amruthapbhat** [sonatype/nexus-book-examples#19]
Hi,

Iam unable to run the provision.sh script as iam getting the below error.

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Script named 'npmBower' will be created
Caught: java.lang.NoClassDefFoundError: org/codehaus/groovy/runtime/typehandling/ShortTypeHandling
java.lang.NoClassDefFoundError: org/codehaus/groovy/runtime/typehandling/ShortTypeHandling
        at org.sonatype.nexus.script.ScriptXO.<init>(ScriptXO.groovy)
        at addUpdateScript.run(addUpdateScript.groovy:69)
Caused by: java.lang.ClassNotFoundException: org.codehaus.groovy.runtime.typehandling.ShortTypeHandling
        ... 2 more

Could you please let me know if there are any pre-requisites that needs to be downloaded

Regards,
Amrutha

**Comment by peterlynch** [comment]
use the latest version of Groovy.
