### ISSUE TITLE
default user login not working for nexus-3.13.0-01

### ISSUE THREAD

**Issue by gsm23** [sonatype/nexus-book-examples#25]
I install the nexus-3.13.0-01 with the bellow changes.

nexus.rc:
  run_as_user="jboss"

nexus.vmoptions:
  -Xms1200M
  -Xmx1200M
  -XX:MaxDirectMemorySize=2G
  -XX:+UnlockDiagnosticVMOptions
  -XX:+UnsyncloadClass
  -XX:+LogVMOutput
  -XX:LogFile=/var/SP/log/nexus/jvm.log
  -XX:-OmitStackTraceInFastThrow
  -Djava.net.preferIPv4Stack=true
  -Dkaraf.home=.
  -Dkaraf.base=.
  -Dkaraf.etc=etc/karaf
  -Djava.util.logging.config.file=etc/karaf/java.util.logging.properties
  -Dkaraf.data=/var/SP/data/nexus
  -Djava.io.tmpdir=/var/SP/data/nexus/tmp
  -Dkaraf.startLocalConsole=false

After I started the nexus withthe above changes the app is running fine but  I am not able to login using the default user and password (admin/admin123)

**Comment by mrprescott** [comment]
This is the github project for the book examples. If you're having a general NXRM issue, I recommend either asking on our ['nexus-users' mailing list](https://groups.google.com/a/glists.sonatype.com/forum/#!forum/nexus-users), filing an issue in the NEXUS project at issues.sonatype.org, or (if you have a license) raising a support ticket.
